export const EmailURL = 'https://script.google.com/macros/s/AKfycbzIb-cFk3OjDH5bugT-f-xz-hiSRyQbtpPvSVy-24DHt3KTxKYPqiRUywHlj1EPksoMQA/exec'
export const SheetsURL = 'https://script.google.com/macros/s/AKfycbzIb-cFk3OjDH5bugT-f-xz-hiSRyQbtpPvSVy-24DHt3KTxKYPqiRUywHlj1EPksoMQA/exec'
export const ReadURL = 'https://script.google.com/macros/s/AKfycbytaHtDwbrL4962Lrx5elqgrmx8INaczQ6EWBKW_9EpkHCLNYKy-FyRZprEArPqS7w/exec'
export const ReadURL2 = 'https://script.google.com/macros/s/AKfycbweyZbc2kl6jOoSCtIYn6VEu-DHZf4QGLnCrme0lWKNQjmkv4s4CsGhNtqfeh2JJxno/exec'
export const FooterURL = 'https://script.google.com/macros/s/AKfycbxYWVhtLbQWqxB6rXkHGpnzqWlG72qNYztW5Upn8mFq_i1Sqrhkah-YbChnK_krAFqb/exec'